basePath: /
definitions:
  http.errorResponse:
    properties:
      message:
        type: string
    type: object
  http.idResponse:
    properties:
      id:
        type: string
    type: object
  http.response:
    properties:
      message:
        type: string
    type: object
  model.Command:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      script:
        type: string
    type: object
  model.CommandInfo:
    properties:
      command:
        $ref: '#/definitions/model.Command'
      command_run:
        $ref: '#/definitions/model.CommandRun'
    type: object
  model.CommandRun:
    properties:
      command_id:
        type: string
      end_time:
        type: string
      exitcode:
        type: integer
      id:
        type: string
      output:
        type: string
      start_time:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for PGPro Application
  title: PGPro App API
  version: "1.0"
paths:
  /api/v1/commands:
    get:
      consumes:
      - application/json
      description: Retrieve all commands
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Command'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Get all commands
      tags:
      - commands
    post:
      consumes:
      - application/json
      description: Create a new command
      parameters:
      - description: Command object
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/model.Command'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.idResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Create a new command
      tags:
      - commands
  /api/v1/commands/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a command by its ID
      parameters:
      - description: Command ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Command'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Get a command by ID
      tags:
      - commands
    put:
      consumes:
      - application/json
      description: Update a command by its ID
      parameters:
      - description: Command ID
        in: path
        name: id
        required: true
        type: string
      - description: Command object
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/model.Command'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Update a command by ID
      tags:
      - commands
  /api/v1/commands/{id}/info:
    get:
      consumes:
      - application/json
      description: Retrieve information about a command by its ID
      parameters:
      - description: Command ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CommandInfo'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Get information about a command by its ID
      tags:
      - commands info
  /api/v1/commands/{id}/stop:
    post:
      consumes:
      - application/json
      description: Stop a command by its ID
      parameters:
      - description: Command ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.errorResponse'
      summary: Stop a command by its ID
      tags:
      - commands info
  /ping:
    get:
      consumes:
      - application/json
      description: Ping endpoint for health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.response'
      summary: Ping endpoint
      tags:
      - ping
swagger: "2.0"
